### ISSUE TITLE
[Consistency review ] Trademark policy White Paper

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/trademark_policy#22]
**Consistency Review notification** - In this phase, the Trademark_policy_White_Paper developed by the WG will be formally reviewed by the GSF members. After this period, the Working Group will address any submitted issues received prior to formally Approving the White Paper
Doc for review - [Trademark_policy_White_Paper](https://github.com/Green-Software-Foundation/trademark_policy/tree/dev/Trademark_policy)

Comments to be submitted in this issue or a PR to be submitted against the dev branch.

NOTE: All comments must be submitted by 28th Sept @ 1200 BST

**Comment by atg-abhishek** [comment]
I've added #23 and #24 as improvements.

**Comment by atg-abhishek** [comment]
And added #25 with minor changes for clarity :)

**Comment by mrchrisadams** [comment]
We have reviewed the changes, and all the submitted requests have been accepted or acted upon.

I'll close this once we have resolved the last branch conflicts in the PRs, but have agreed on the content.

**Comment by mrchrisadams** [comment]
OK, last changes are merged in. Thanks folks 👍
