### ISSUE TITLE
Acceptable use - use of the foundation name, and "green software"

### ISSUE THREAD

**Issue by mrchrisadams** [Green-Software-Foundation/trademark_policy#6]
Because _green_ in the context of green energy is already quite a minefield in terms of what it actually means, the idea of _green software_, is likely to be similarly subjective.

This is especially the case when used by a wide range of companies who you might not associate with being green. 

Like the other issues, this is a reminder for further discussion, or at least to tighten up the scope for use of "green software", so it has _some_ meaning.

Given "green software" is part of the name of the foundation, we are likely going to need to have some guidance on the use of this term - it wouldn't be leap to imagine people being confused when non-affiliated groups use the term.

**Comment by jawache** [comment]
Agreed, we've got the manifesto which is being worked on, that would be the right place (or one of the places). 

In fact, there is an exacting definition in the SCI spec that I'm starting to love "[reducing] the total change in global emissions associated with a particular piece of software".

**Comment by aecurrie** [comment]
I like the definition, but I'd like to push for something else in addition, somewhat inspired by the Bill Gates book here ;-) He makes the correct point that reducing is not the goal. It's eliminating or at least highly radical reduction (particularly in the software industry). That's far harder, it'll take longer and you'd do it in different architectural ways, but "reducing" may be too easy a win. It might actually get in the way of the bigger goal by distracting effort on something that doesn't get us where we need to be. For example, the the recent Google paper you posted @jawache they remind us of the need to rearchitect systems to separate out and maximize use of latency insensitive tasks ("spot" tasks) for green DC operation. I'm not averse to quick wins, but how do we remind folk that mere reduction is not the goal? What's their plan for zero?

**Comment by mrchrisadams** [comment]
There are some fairly clear positions embedded in the SCI already, and a lot of work has gone into building consensus here.

We can make a position paper from this, 'extracted' from what we have consensus on in the SCI so far.
